### ISSUE TITLE
Improve contributing process

### ISSUE THREAD

**Issue by AdamVig** [Juravenator/restify-json-hal#5]
- [ ] Add Contributing section to `README` or as its own file (`CONTRIBUTING`)
- [ ] Add `.editorconfig` to ensure that indentation and file endings are consistent
- [ ] Add linting configuration (probably [ESLint](http://eslint.org/)) to help prevent bugs
- [ ] Choose a code style that a linter can enforce (I like [JavaScript Standard Style](http://standardjs.com/))
- [ ] Add continuous integration to ensure that every pull request meets all standards

The above points are all up for discussion and I am willing to implement them if @Juravenator agrees that they would improve the process for contributions.

This library is going to be helpful for me on a current project and hopefully other projects in the future, so I want to help improve it for myself and others.

**Comment by AdamVig** [comment]
@Juravenator any feedback on the points above? As I mentioned, I am willing to put in the work, but since you are the maintainer I do not want to spend time on anything you are not willing to merge.

**Comment by Juravenator** [comment]
Hi @AdamVig

I completely agree on all of these points, and that each one helps to ease the contribution process :) 

It appears you are more experienced in this than me (I didn't even know that `.editorconfig` existed), so suggestions on how to proceed in this are greatly appreciated!

On a sour note, I do generally not agree with strict code styles like JS Standard.  
For example, I lately use the [Stroustrup](https://en.wikipedia.org/wiki/Indent_style#Variant:_Stroustrup) brace style because it makes for cleaner git diffs.  
I also wouldn't want to discourage contributions because of petty rules like [never use semicolon](http://eslint.org/docs/rules/semi) or [always use single quotes](http://eslint.org/docs/rules/quotes).

But in general, yes, a coding standard is nice. Just to keep order in obvious matters, not to assert dominance on contributors.
